apiVersion: v1 # Load balancer AWS to connect from web
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - nodePort: 31000 
      port: 80
      targetPort: 80
  type: LoadBalancer