apiVersion: v1 # Load balancer 
kind: Service
metadata:
  name: nodejs-web-service
spec:
  selector:
    app: nodejs-web
  ports:
    - nodePort: 31000 
      port: 3000
      targetPort: 3000
  type: LoadBalancer